version: "3.9"

services:
  backend:
    build: ./app
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: nicegui_frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  worker:
    build: ./inference
    container_name: celery_worker
    command: celery -A infer worker --loglevel=info -c 1
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

